package dev.yjs;

import dev.yjs.lib0.Json;
import dev.yjs.test.T;
import dev.yjs.utils.Doc;
import dev.yjs.utils.Updates;
import org.junit.jupiter.api.Test;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

/**
 * Port of tests/compatibility.tests.js. Decodes updates generated by <b>Yjs v13.2.0</b> (an older
 * version, from randomized tests) and verifies the document content is reproduced exactly —
 * validating backward-compatible decoding/integration of array, nested map, and rich text (with
 * embeds and formatting).
 */
public class CompatibilityTest {

    static byte[] b64(String resource) throws Exception {
        try (InputStream in = CompatibilityTest.class.getResourceAsStream(resource)) {
            String s = new String(in.readAllBytes(), StandardCharsets.UTF_8).trim();
            return Base64.getDecoder().decode(s);
        }
    }

    static Object json(String resource) throws Exception {
        try (InputStream in = CompatibilityTest.class.getResourceAsStream(resource)) {
            String s = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            return Json.parse(s);
        }
    }

    @Test
    void arrayCompatibilityV1() throws Exception {
        Doc doc = new Doc();
        Updates.applyUpdate(doc, b64("/compat_array.b64"));
        T.compare(doc.getArray("array").toJSON(), json("/compat_array.json"), "array v13.2.0 decode");
    }

    @Test
    void mapDecodingCompatibilityV1() throws Exception {
        Doc doc = new Doc();
        Updates.applyUpdate(doc, b64("/compat_map.b64"));
        T.compare(doc.getMap("map").toJSON(), json("/compat_map.json"), "map v13.2.0 decode");
    }

    @Test
    void textDecodingCompatibilityV1() throws Exception {
        Doc doc = new Doc();
        Updates.applyUpdate(doc, b64("/compat_text.b64"));
        T.compare(doc.getText("text").toDelta(), json("/compat_text.json"), "text v13.2.0 decode");
    }
}
